services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\UserStateAccessControl\Conditional\CacheControl\TypeResolverDecorators\:
        resource: '../../../src/Conditional/CacheControl/TypeResolverDecorators/*'
        public: true

    PoP\UserStateAccessControl\Conditional\CacheControl\Hooks\:
        resource: '../../../src/Conditional/CacheControl/Hooks/*'
        public: true
